# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "bioregistry>=0.13.35",
#     "click>=8.3.2",
#     "tabulate>=0.10.0",
# ]
# ///

"""Update collections."""

import datetime
import os
from pathlib import Path
from textwrap import dedent

import bioregistry
import bioregistry.version
import click
from bioregistry.constants import NFDI_ROR
from tabulate import tabulate

HERE = Path(__file__).parent.resolve()
ROOT = HERE.parent.resolve()
ONTOLOGIES = ROOT.joinpath("docs", "meta", "wg_onto", "used-ontologies").resolve()

RENAMES = {"text+": "text-plus", "berd@nfdi": "berd-nfdi"}


@click.command()
def main() -> None:
    for path in ONTOLOGIES.glob("*.md"):
        path.unlink()

    today = datetime.date.today().strftime("%Y-%m-%d")
    generation = f"Automatically generated by Semantic Farm v{bioregistry.version.get_version()} on {datetime.date.today()}"

    index_rows = []
    for collection in bioregistry.read_collections().values():
        if not collection.has_organization_with_ror(NFDI_ROR):
            continue
        if len(collection.resources) < 2:
            continue

        name = collection.name.removesuffix(" Collection").strip()
        key = RENAMES.get(name.lower(), name.lower())

        path = ONTOLOGIES.joinpath(key).with_suffix(".md")

        text = dedent(f"""\
        ---
        title: {name}
        ---

        This page was automatically generated on {today} using Semantic Farm v{bioregistry.version.get_version()}.
        See this collection in the [Semantic Farm](https://semantic.farm/collection/{collection.identifier}).

        Suggest a new addition to this collection [here](https://github.com/biopragmatics/bioregistry/issues/new?template=add-collection-prefix.yml&collection={collection.identifier}&title=Add%20prefix%20X%20to%20collection%20{collection.identifier}).
        """)
        text += "\n\n"

        if collection.maintainers:
            text += "This collection is maintained by:\n\n"
            for maintainer in collection.maintainers:
                text += f"- [{maintainer.name.strip()}](https://semantic.farm/orcid:{maintainer.orcid})\n"
            text += "\n"

        rows = []

        has_comments = any(
            annotation.comment for annotation in collection.get_annotated_prefixes()
        )

        for annotation in collection.get_annotated_prefixes():
            resource = bioregistry.get_resource(annotation.prefix, strict=True)

            license = resource.get_license()
            if license and license.startswith("http"):
                license = f"[Custom]({license})"

            parts = [
                f"[`{resource.get_preferred_prefix() or resource.prefix}`](https://semantic.farm/{resource.prefix})",
                resource.get_name(),
                license,
            ]
            if has_comments:
                parts.append(annotation.comment)
            rows.append(tuple(parts))

        headers = ["Prefix", "Name", "License"]
        if has_comments:
            headers.append("Comment")
        text += tabulate(rows, headers=headers, tablefmt="github")
        text += "\n"
        path.write_text(text)

        index_rows.append(
            (
                f"[{name}](/docs/meta/wg_onto/used-ontologies/{path.name})",
                len(collection.resources),
                ", ".join(sorted(m.name for m in collection.maintainers or [])),
            )
        )

    index_text = dedent(f"""\
    ---
    title: Used Ontologies
    ---

    {generation}. See source data at https://semantic.farm/collection/?ror=05qj6w324.
    """)

    index_text += "\n\n"
    index_text += tabulate(
        sorted(index_rows),
        headers=["Consortium", "# Ontologies", "Collection Maintainers"],
        tablefmt="github",
    )
    index_text += "\n"

    ONTOLOGIES.joinpath("index.md").write_text(index_text)

    os.system(
        f"npx --yes prettier --check --prose-wrap always --write '{ONTOLOGIES}/*.md'"
    )


if __name__ == "__main__":
    main()
