# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "bioregistry>=0.13.35",
#     "click>=8.3.2",
#     "tabulate>=0.10.0",
# ]
# ///

"""Update collections."""

import datetime
from textwrap import dedent
from pathlib import Path
import bioregistry
import bioregistry.version
from bioregistry.constants import NFDI_ROR
import click
from tabulate import tabulate

HERE = Path(__file__).parent.resolve()
ROOT = HERE.parent.resolve()
ONTOLOGIES = ROOT.joinpath("docs", "meta", "wg_onto", "used-ontologies")

RENAMES = {"text+": "text-plus", "berd@nfdi": "bern-nfdi"}


@click.command()
def main() -> None:
    for path in ONTOLOGIES.glob("*.md"):
        path.unlink()

    generation = f"Automatically generated by Semantic Farm v{bioregistry.version.get_version()} on {datetime.date.today()}"

    index_rows = []
    for collection in bioregistry.read_collections().values():
        if not collection.has_organization_with_ror(NFDI_ROR):
            continue
        if len(collection.resources) < 2:
            continue

        name = collection.name.removesuffix(" Collection").strip()
        key = RENAMES.get(name.lower(), name.lower())

        path = ONTOLOGIES.joinpath(key).with_suffix(".md")

        text = dedent(f"""\
        ---
        title: {name}
        ---
        """)
        text += "\n\n"

        rows = []
        for annotation in collection.get_annotated_prefixes():
            resource = bioregistry.get_resource(annotation.prefix, strict=True)
            rows.append((
                f"[`{resource.prefix}`](https://semantic.farm/{resource.prefix})",
                resource.get_name(),
                resource.get_license(),
                annotation.comment
            ))
        text += tabulate(rows, headers=['Prefix', "Name", "License", "Comment"], tablefmt="github")
        text += "\n"
        path.write_text(text)

        index_rows.append((
            f'[{name}](/docs/meta/wg_onto/used-ontologies/{path.name})',
            len(collection.resources),
            ", ".join(sorted(m.name for m in collection.maintainers or []))
        ))

    index_text = dedent(f"""\
    ---
    title: Used Ontologies
    ---

    {generation}. See source data at https://semantic.farm/collection/?ror=05qj6w324.
    """)

    index_text += "\n\n"
    index_text += tabulate(index_rows, headers=["Consortium", "# Ontologies", "Maintainers"], tablefmt="github")
    index_text += "\n"

    ONTOLOGIES.joinpath("index.md").write_text(index_text)

if __name__ == '__main__':
    main()
